### ISSUE TITLE
Custom Ad notification on iPad

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1916]
### Description: 
Implement a more native look and feel for the ad notification on iPad

Note: Onboarding may need to change too to accommodate this

**Comment by kylehickinson** [comment]
Needs more information as to what this change is

**Comment by anthonypkeane** [comment]
The notification width, on iPad, should be 40% of the width of the longest screen dimension.
So, if the screen is 1000x600, the width should be 400px in both landscape and portrait.

**Comment by kjozwiak** [comment]
Comparison of the ad sizes on `iPad` after this fix landed for comparison:

#### Old size of ads using `1.13 (19.11.06.18)` which is the current release:

<img width="612" alt="Screen Shot 2019-11-25 at 2 43 20 PM" src="https://user-images.githubusercontent.com/2602313/69572386-07e03f00-0f92-11ea-9c92-bcce315aa19d.png">

<img width="629" alt="Screen Shot 2019-11-25 at 2 43 56 PM" src="https://user-images.githubusercontent.com/2602313/69572385-07e03f00-0f92-11ea-9805-63e788c77773.png">

#### New size of ads using `1.14 (19.11.22.15)` which is the current release:

**Ads received while in portrait mode:**

<img width="710" alt="Screen Shot 2019-11-25 at 2 46 24 PM" src="https://user-images.githubusercontent.com/2602313/69572592-70c7b700-0f92-11ea-858b-bf278bc8bf8b.png">

<img width="692" alt="Screen Shot 2019-11-25 at 2 46 44 PM" src="https://user-images.githubusercontent.com/2602313/69572591-70c7b700-0f92-11ea-8000-d9eb2afcab6b.png">

**Ads received while in landscape mode:**

![IMG_0092](https://user-images.githubusercontent.com/2602313/69575544-7c1de100-0f98-11ea-95f7-3046533d6aab.PNG)

![IMG_0093](https://user-images.githubusercontent.com/2602313/69575543-7c1de100-0f98-11ea-9f64-e75be090e3a1.PNG)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPad Air 3rd Gen` running `iOS 13.3` using `1.14 (19.11.22.15)`
* ensured that you can click on the `First Time Ad` without any issues once it's displayed
* ensured that ads are being displayed and are using the new width as mentioned via https://github.com/brave/brave-ios/issues/1916#issuecomment-558313113 while using both `portrait` and `landscape` modes
* ensured that you can tap on ads when they first appear and the `Ads` section in `Rewards` is updated

Verification **PASSED** on `iPad Mini 4` running `iOS 12.4.1` using `1.14 (19.11.22.15)`
* ensured that you can click on the `First Time Ad` without any issues once it's displayed
* ensured that ads are being displayed and are using the new width as mentioned via https://github.com/brave/brave-ios/issues/1916#issuecomment-558313113 while using both `portrait` and `landscape` modes
* ensured that you can tap on ads when they first appear and the `Ads` section in `Rewards` is updated

**Comment by kjozwiak** [comment]
@Brandon-T any new updates re: why @srirambv isn't seeing the new width for ad notifications? I spent a few going through this on both `iOS 12` & `iOS 13` and it seems to be working. Also added comparisons via https://github.com/brave/brave-ios/issues/1916#issuecomment-558313113.

I'l wait till we figure out what's happening with @srirambv before adding the `QA Pass - iPad` label.

**Comment by srirambv** [comment]
I still have issues with the size of the ad
Sample ad on clean install in portrait  mode
![image](https://user-images.githubusercontent.com/17010094/69579235-16cdee00-0fa0-11ea-8dc0-93758769ec44.png)
Actual ad notification in landscape
![image](https://user-images.githubusercontent.com/17010094/69579252-20575600-0fa0-11ea-9e86-d25707f85728.png)

It looks like the change in orientation causes the ad to show up in smaller size. @Brandon-T @kylehickinson I did get the sample ad notification in landscape mode and then changed orientation to portrait before the actual ad showed up and it looks smaller compared to the new spec

**Comment by srirambv** [comment]
Marking as QA/Pass based on https://github.com/brave/brave-ios/issues/1916#issuecomment-558313113. Logged followup issue #2027 for ad notification size change on device orientation
